[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXTAUTH_URL = "https://forosas.netlify.app"
  PAYPAL_MODE = "live"

[[plugins]]
  package = "@netlify/plugin-nextjs"
